version: '2'
services:
    tn-app:
        image: tn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tn-mysql:3306/tn?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tn-elasticsearch:9300
        ports:
            - 8080:8080
    tn-mysql:
        extends:
            file: mysql.yml
            service: tn-mysql
    tn-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tn-elasticsearch
