package eu.canpack.fip.bo.audit;

/**
 * CP S.A.
 * Created by lukasz.mochel on 24.02.2018.
 */
public enum AuditedOperation {
    CREATED,
    CREATED_AND_SEND_TO_ESTIMATION,
    UPDATED,
    UPDATED_AND_SEND_TO_ESTIMATION,
    UPDATED_BY_ADMIN,
    INQUIRY_SEND_TO_ESTIMATION,
    CLAIMED_ESTIMATION,
    UNCLAIMED_ESTIMATION,
    MOVED_TO_ARCHIVE,
    MOVED_TO_PRODUCTION,
    FILLED_SAP_NUMBER,
    CLONED,
    MARK_FINISHED,
    RETURN_TO_TECHNOLOGY_VERIFICATION,
    RETURN_TO_TECHNOLOGY_CREATION,
    RETURN_TO_PRODUCTION
}
